# 1. Globale Website-Einstellungen
title: Malapascua.asia
email: Ihre-E-Mail-Adresse # Optional

# 2. Basis-URL (WICHTIG für Sitemap)
# Muss Ihre vollständige, von Google indexierte Domain sein
url: "https://www.malapascua.asia"
baseurl: "" # Bleibt leer, da Sie eine benutzerdefinierte Domain verwenden

# 3. Das offizielle Sitemap-Plugin aktivieren
plugins:
  - jekyll-sitemap

# 4. (Optional) Das Theme einstellen, falls Sie eines verwenden
# theme: minima # Beispiel-Theme